name: presensiblebeacon
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter_icons:
  image_path: "assets/png/SplashPage_LogoAtmaJaya.png" 
  android: true
  ios: true

dependencies:
  flutter:
    sdk: flutter

  # Icon Launcher
  flutter_launcher_icons: "^0.9.0"

  # Ikon dan Font
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0

  # Animasi progress dalam bentuk shimmer.
  shimmer: ^2.0.0

  # Bluetooth On / Off.
  flutter_blue: ^0.8.0

  # Memanggil sistem untuk menghidupkan bluetooth.
  system_setting: ^0.1.3

  # Fungsi Scanning Bluetooth.
  flutter_beacon: ^0.5.0
  
  # API.
  http: ^0.12.1
  shared_preferences: ^2.0.5

  # Transisi halaman dan routing.
  get: ^4.1.4
  
  # Jam
  intl: ^0.17.0

  # Menampilkan peringatan dalam bentuk toast.
  fluttertoast: ^8.0.7
  
  # Menampilkan animasi progress login pada login
  flutter_progress_hud: ^2.0.0

  # Permission GPS, Location
  permission_handler: ^4.4.0+hotfix.2

  # Tampilan Slider Carousel
  carousel_slider: ^3.0.0
  
  # Cek Koneksi Internet
  connectivity: ^3.0.6

  # Cek String sama
  string_similarity: ^2.0.0
  
  flutter_advanced_avatar: ^1.0.0+1

  flutter_initicon: ^2.0.0

# Cadangan Package
  # provider: ^5.0.0
  # path_provider: ^2.0.1
  # beacons_plugin: ^2.0.0
  # flutter_spinkit: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/images/error_icon.png
    - assets/images/background1.jpg
    - assets/images/not_found_icon.png

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
